/* NarrowBorne — catálogo estático. Sem dependências, rastreadores ou servidor. */
(() => {
'use strict';
const products = window.CATALOG_PRODUCTS || [];
const brands = window.CATALOG_BRANDS || [];
const brandLogos = window.CATALOG_BRAND_LOGOS || {};
const config = window.STORE_CONFIG || {};
const categories = {camisetas:'Camisetas',moletons:'Moletons',calcas:'Calças',bones:'Bonés'};
const main=document.getElementById('conteudo');
const observer='IntersectionObserver' in window?new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-revealed');observer.unobserve(entry.target);}}),{threshold:.08}):null;
const heart='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/></svg>';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const imagePath=v=>'assets/images/'+v;
let favorites=[];
try{const stored=JSON.parse(localStorage.getItem('narrowborne:favoritos')||'[]');if(Array.isArray(stored))favorites=stored.filter(id=>products.some(p=>p.id===id));}catch{}
const favButton=p=>`<button class="favorite" data-favorite="${esc(p.id)}" aria-pressed="${favorites.includes(p.id)}" aria-label="${favorites.includes(p.id)?'Remover dos':'Adicionar aos'} favoritos: ${esc(p.name)}">${heart}</button>`;
function card(p){return `<article class="product-card reveal"><a class="product-photo" href="#/produto/${esc(p.id)}" aria-label="Ver ${esc(p.brand+' '+p.name)}"><span class="product-label">NARROWBORNE</span><img src="${imagePath(p.image)}" alt="${esc(p.brand+' — '+p.name)}" loading="lazy" width="600" height="760"></a>${favButton(p)}<div class="product-info"><a class="product-brand" href="${catalogUrl({marca:p.brand})}">${esc(p.brand)}</a><h3><a href="#/produto/${esc(p.id)}">${esc(p.name)}</a></h3><div class="product-bottom"><span>${esc(p.color)}</span><a href="#/produto/${esc(p.id)}">Explorar ↗</a></div></div></article>`;}
const grid=items=>`<div class="product-grid">${items.map(card).join('')}</div>`;
function catalogUrl(values={}){const q=new URLSearchParams();Object.entries(values).forEach(([k,v])=>{if(v)q.set(k,v);});return '#/catalogo'+(q.size?'?'+q.toString():'');}
function breadcrumb(items=[]){return `<nav class="breadcrumbs" aria-label="Caminho da página"><a href="#/">Início</a>${items.map(x=>`<span aria-hidden="true">/</span>${x.url?`<a href="${esc(x.url)}">${esc(x.text)}</a>`:`<span aria-current="page">${esc(x.text)}</span>`}`).join('')}</nav>`;}
function pageTop(title,description='',crumbs){return `<div class="page-top"><div class="wrap">${breadcrumb(crumbs||[{text:title}])}<h1>${esc(title)}</h1>${description?`<p>${esc(description)}</p>`:''}</div></div>`;}
function empty(title,text,link='#/catalogo',label='Explorar todas as peças'){return `<div class="empty"><h2>${esc(title)}</h2><p>${esc(text)}</p><a class="btn" href="${esc(link)}">${esc(label)} ↗</a></div>`;}
function brandTiles(){return `<div class="brands-grid">${brands.map((b,i)=>`<a class="brand-tile reveal brand-${i}" href="${catalogUrl({marca:b})}" aria-label="Ver seleção ${esc(b)}"><span class="brand-number">${String(i+1).padStart(2,'0')}</span><img class="brand-logo" src="${imagePath('brands/'+brandLogos[b])}" alt="${esc(b)}" width="320" height="120" loading="lazy"><span class="brand-arrow" aria-hidden="true">↗</span></a>`).join('')}</div>`;}
function home(){return `
<section class="hero ink-hero"><img class="hero-bg" src="assets/images/ink-hero.png" alt="" width="1536" height="1024" fetchpriority="high"><div class="hero-grain" aria-hidden="true"></div><span class="hero-index">MULTIMARCAS / SÃO PAULO</span><div class="wrap hero-content"><span class="eyebrow">CURADORIA NARROWBORNE</span><h1>DA ROTINA<br>PRO ROLÊ.<br><em>SEM TROCAR DE ESTILO.</em></h1><p>Peças urbanas de diferentes marcas, escolhidas para funcionar juntas — do básico bem cortado ao street que chama atenção.</p><div class="hero-actions"><a class="btn purple" href="#/marcas">VER AS MARCAS <span>↗</span></a><a class="text-link light" href="#/catalogo">Explorar categorias ↗</a></div></div><div class="hero-stamp"><span>SELEÇÃO NARROWBORNE</span><strong>PEÇA POR PEÇA.<br>SEM ENCHER CATÁLOGO.</strong></div><a class="scroll-cue" href="#/catalogo">VEJA O QUE ESTÁ CHEGANDO <span>↓</span></a></section>
<div class="marquee" aria-hidden="true"><div class="marquee-track">${Array.from({length:4},()=>'<span>CURADORIA MULTIMARCAS.<b>✳</b></span><span>CATÁLOGO EM PREPARAÇÃO.<b>✳</b></span>').join('')}</div></div>
<section class="section wrap"><div class="section-head"><div><span class="eyebrow">01 / COMECE PELA PEÇA</span><h2>MONTE O LOOK<br><em>POR CATEGORIA.</em></h2></div><span class="section-note">Quatro pontos de partida.</span></div><div class="category-grid type-categories">${Object.entries(categories).map(([key,label],i)=>`<a class="category reveal" href="${catalogUrl({categoria:key})}"><span class="category-num">0${i+1} /</span><span class="category-watermark" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><span class="category-status">CATÁLOGO SENDO MONTADO</span><div class="category-caption">${label}<span>↗</span></div></a>`).join('')}</div></section>
<section class="section edit-section wrap" aria-label="Campanhas NarrowBorne"><div class="editorial-grid"><a href="#/colecao/street" class="editorial ink-campaign reveal"><img src="assets/images/ink-campaign.png" alt="" width="1536" height="1024" loading="lazy"><span class="editorial-number">N/B — EDIT 01</span><div class="editorial-copy"><span class="eyebrow">ROUPA PARA ACOMPANHAR A CIDADE</span><h2>CONFORTO PRA SAIR.<br><em>PRESENÇA PRA FICAR.</em></h2><span class="text-link">Conheça a seleção street ↗</span></div></a><a href="#/sobre" class="editorial logo-campaign reveal"><img src="assets/images/nb-emblem.png" alt="Monograma NB original da NarrowBorne" width="1024" height="1024" loading="lazy"><span class="editorial-number">N/B — CURADORIA</span><div class="editorial-copy"><span class="eyebrow">O CRITÉRIO VEM ANTES DA QUANTIDADE</span><h2>UMA LOJA.<br>VÁRIAS REFERÊNCIAS.</h2><span class="text-link">Como a Narrowborne escolhe ↗</span></div></a></div></section>
<section class="section wrap brands-home"><div class="section-head"><div><span class="eyebrow">02 / MARCAS NO NOSSO RADAR</span><h2>ESCOLHA A MARCA.<br><em>A GENTE ORGANIZA O RESTO.</em></h2></div><a class="text-link" href="#/marcas">Ver a lista completa ↗</a></div>${brandTiles()}<p class="note">Os logotipos identificam as marcas previstas para o catálogo. A disponibilidade será informada em cada produto publicado.</p></section>
<section class="statement-band"><div class="wrap"><span class="eyebrow">NOSSA REGRA PARA O CATÁLOGO</span><p>MENOS ENCHIMENTO.<br><span>MAIS PEÇA BOA.</span></p><a class="btn outline" href="#/sobre">ENTENDA A PROPOSTA ↗</a></div></section>
${watchBlock(false)}
<section class="section wrap identity"><div><span class="eyebrow">03 / PRECISA DE AJUDA?</span><h2>VOCÊ ESCOLHE.<br>A GENTE CONFIRMA.</h2></div><div><p>Antes da compra, fale com a loja para conferir medida, estoque, prazo e entrega da peça que chamou sua atenção.</p><a class="text-link" href="#/atendimento">Abrir atendimento ↗</a></div></section>`;}

function watchBlock(full){return `<section class="watch-section"><div class="wrap watch-inner"><div><span class="coming-label">EM BREVE</span><h${full?'1':'2'} class="watch-title">O DETALHE QUE<br><span>FECHA O VISUAL.</span></h${full?'1':'2'}><div class="watch-copy"><p>A categoria de relógios ainda está sendo preparada.<br>Quando entrar no ar, modelos e disponibilidade aparecerão aqui.</p><a class="text-link light" href="${full?'#/catalogo':'#/relogios'}">${full?'Voltar às categorias':'Ver a prévia da categoria'} ↗</a></div></div><div class="watch-abstract" aria-hidden="true"><div class="watch-numeral">SOON.</div><div class="watch-meta"><span>NARROWBORNE / RELÓGIOS</span><span>EM PREPARAÇÃO</span></div></div></div></section>`;}
function catalog(params){const category=params.get('categoria')||'',brand=params.get('marca')||'',q=params.get('q')||'',sort=params.get('ordem')||'selecao';
const current={categoria:category,marca:brand,q,ordem:sort==='selecao'?'':sort};
let filtered=products.filter(p=>(!category||p.category===category)&&(!brand||norm(p.brand)===norm(brand))&&(!q||norm(p.name+' '+p.brand+' '+categories[p.category]+' '+p.color).includes(norm(q))));
if(sort==='az')filtered.sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));if(sort==='marca')filtered.sort((a,b)=>a.brand.localeCompare(b.brand,'pt-BR'));
const title=q?`Busca: ${q}`:brand||categories[category]||'Todas as peças';
return `${pageTop(title,'Seu próximo estilo está chegando.')}<div class="wrap catalog-layout"><aside class="filters" aria-label="Filtros do catálogo"><div class="filter-group"><h2 class="filter-title">Categorias</h2><a class="${!category?'active':''}" href="${catalogUrl({...current,categoria:''})}">Todas as peças<span>${products.length}</span></a>${Object.entries(categories).map(([k,v])=>`<a class="${category===k?'active':''}" href="${catalogUrl({...current,categoria:k})}">${v}<span>${products.filter(p=>p.category===k).length}</span></a>`).join('')}</div><div class="filter-group"><label class="filter-title" for="brand-filter">Sua marca</label><select id="brand-filter"><option value="">Todas as marcas</option>${brands.map(b=>`<option ${norm(brand)===norm(b)?'selected':''} value="${esc(b)}">${esc(b)}</option>`).join('')}</select></div><div class="filter-group"><span class="filter-title">PRÓXIMO CAPÍTULO</span><a href="#/relogios">Relógios ↗</a><a href="#/acessorios">Correntes e acessórios ↗</a></div></aside><section aria-label="Peças encontradas"><div class="catalog-toolbar"><span role="status">${filtered.length} ${filtered.length===1?'peça publicada':'peças publicadas'}</span><label>Ordenar <select class="sort-select" id="sort-filter"><option value="selecao" ${sort==='selecao'?'selected':''}>Nossa seleção</option><option value="az" ${sort==='az'?'selected':''}>Nome: A–Z</option><option value="marca" ${sort==='marca'?'selected':''}>Marca: A–Z</option></select></label></div>${category||brand||q?`<div class="active-filters">${category?`<a class="filter-chip" aria-label="Remover filtro ${esc(categories[category]||category)}" href="${catalogUrl({...current,categoria:''})}">${esc(categories[category]||category)} ×</a>`:''}${brand?`<a class="filter-chip" aria-label="Remover marca ${esc(brand)}" href="${catalogUrl({...current,marca:''})}">${esc(brand)} ×</a>`:''}${q?`<a class="filter-chip" aria-label="Remover busca" href="${catalogUrl({...current,q:''})}">${esc(q)} ×</a>`:''}<a class="filter-chip" href="#/catalogo">Limpar filtros</a></div>`:''}${filtered.length?grid(filtered):empty('O próximo drop está chegando.',q?'Nenhuma peça publicada corresponde à busca. Nosso catálogo está em preparação.':brand?`A seleção ${brand} está em preparação. As peças aparecerão aqui quando forem publicadas.`:'Estamos preparando esta seleção. Volte em breve para descobrir as novidades.','#/marcas','Conhecer as marcas')}<p class="note"></p></section></div>`;}
function product(id){const p=products.find(x=>x.id===id);if(!p)return notFound();return `<section class="wrap section" style="padding-top:27px">${breadcrumb([{text:categories[p.category],url:catalogUrl({categoria:p.category})},{text:p.brand,url:catalogUrl({marca:p.brand})},{text:p.name}])}<div class="product-detail"><div class="detail-photo"><img src="${imagePath(p.image)}" alt="${esc(p.brand+' '+p.name)}" width="900" height="1000" fetchpriority="high"><span class="photo-note">Foto da peça</span></div><div class="detail-copy"><a class="product-brand" href="${catalogUrl({marca:p.brand})}">${esc(p.brand)} ↗</a><h1>${esc(p.name)}</h1><span class="reference">SELEÇÃO NARROWBORNE / ${esc(p.id.toUpperCase())}</span><p>${esc(p.description)}</p><div class="size-label"><span>Cor: <strong>${esc(p.color)}</strong></span></div><div class="size-label"><span>Tamanho de interesse</span><a href="#/ajuda">Como escolher?</a></div><div class="sizes" role="group" aria-label="Tamanho de interesse">${p.sizes.map(s=>`<button class="size" data-size="${esc(s)}" aria-pressed="false">${esc(s)}</button>`).join('')}</div><div class="detail-actions"><a class="btn" id="interest-link" href="#/atendimento?peca=${encodeURIComponent(p.id)}">TENHO INTERESSE ↗</a>${favButton(p)}</div><p class="detail-disclaimer">Peça de referência. Cores, tamanhos e disponibilidade precisam ser confirmados com a loja.</p><details open><summary>Sobre esta seleção</summary><p>${esc(p.description)} Esta página apresenta uma referência para o futuro catálogo. A composição, as medidas e os detalhes da peça comercializada serão informados pela loja.</p></details><details><summary>Como consultar uma peça</summary><p>Escolha seu tamanho de interesse e toque em “Tenho interesse” para preparar sua consulta. Nenhum pedido ou pagamento é realizado neste site.</p></details><details><summary>Entrega e trocas</summary><p>Frete, prazo e condições de troca devem ser confirmados com o atendimento antes de qualquer compra.</p></details></div></div><div class="section-head"><div><span class="eyebrow">COMPLETE A SUA SELEÇÃO</span><h2>TAMBÉM É A SUA CARA.</h2></div><a class="text-link" href="#/catalogo">Ver tudo ↗</a></div>${grid(products.filter(x=>x.id!==p.id).sort((a,b)=>(b.category===p.category)-(a.category===p.category)).slice(0,4))}</section>`;}
function brandPage(){return `${pageTop('Marcas selecionadas.','Quatorze nomes previstos para compor o catálogo da Narrowborne.')}<section class="section wrap">${brandTiles()}<p class="note">A presença de uma marca nesta página não indica parceria oficial nem estoque disponível. Cada peça será anunciada somente após confirmação da loja.</p></section>`;}

function collection(id){const types={street:{title:'A rua é sua.',sub:'Street selection / Edit 01',text:'Presença, conforto e personalidade. Explore moletons, calças e peças que conversam com o ritmo da cidade.',filter:p=>p.collections.includes('street')},essenciais:{title:'O básico. Nada óbvio.',sub:'Essential selection / Edit 02',text:'Cores fáceis de combinar. Peças para levar do primeiro compromisso ao último encontro.',filter:p=>p.collections.includes('essenciais')},minimal:{title:'Menos. Mas melhor.',sub:'Minimal selection / Edit 03',text:'Linhas simples e tons neutros. Uma seleção para quem deixa o estilo falar nos detalhes.',filter:p=>p.collections.includes('minimal')}};const c=types[id];if(!c)return notFound();return `<section class="collection-intro"><div class="wrap">${breadcrumb([{text:'Coleções'},{text:c.title}])}<span class="eyebrow">${c.sub}</span><h1>${c.title}</h1><p>${c.text}</p></div></section><section class="section wrap">${products.filter(c.filter).length?grid(products.filter(c.filter)):empty('Estilo em construção.','Nossa próxima seleção está em preparação. Em breve, peças para deixar a sua marca.','#/marcas','Conhecer as marcas')}<p class="note"></p></section>`;}
function saved(){const items=products.filter(p=>favorites.includes(p.id));return `${pageTop('Sua seleção.','As peças que você curtiu, reunidas em um só lugar.')}<section class="section wrap">${items.length?grid(items):empty('Seu estilo começa aqui.','Quando as peças forem publicadas, você poderá salvar as suas favoritas aqui.')}<p class="note">Seus favoritos ficam salvos apenas neste navegador. Não é necessário criar uma conta.</p></section>`;}
function accessories(){return `${pageTop('O detalhe muda tudo.','Bonés, correntes e acessórios para completar sua identidade.')}<section class="section wrap"><div class="accessory-grid"><article class="accessory-tile"><span class="eyebrow">01 / A SELEÇÃO</span><h2>BONÉS.</h2><p>O toque final que acompanha o seu ritmo.</p><a class="text-link" href="#/catalogo?categoria=bones">Explorar bonés ↗</a></article><article class="accessory-tile"><span class="eyebrow">02 / EM PREPARAÇÃO</span><h2>CORRENTES.</h2><p>Uma nova seleção está sendo preparada.</p><a class="text-link" href="#/atendimento?assunto=Correntes">Consultar novidades ↗</a></article><article class="accessory-tile dark"><span class="eyebrow" style="color:var(--lilac)">03 / EM BREVE</span><h2>RELÓGIOS.</h2><p>Seu próximo capítulo tem hora marcada.</p><a class="text-link light" href="#/relogios">Conheça a categoria ↗</a></article></div></section>`;}
function contact(params){const p=products.find(p=>p.id===params.get('peca'));const size=params.get('tamanho');const topic=params.get('assunto');const message=p?`Olá, NarrowBorne! Tenho interesse na peça ${p.brand} — ${p.name} (${p.id}).${size?' Tamanho de interesse: '+size+'.':''} Vocês podem confirmar a disponibilidade e os detalhes?`:`Olá, NarrowBorne! Gostaria de saber mais sobre ${topic||'a seleção de peças e a disponibilidade do catálogo'}.`;const wa=String(config.whatsapp||'').replace(/\D/g,'');const active=/^\d{10,15}$/.test(wa);const insta=/^https:\/\/(www\.)?instagram\.com\//i.test(config.instagram||'');return `${pageTop('Vamos conversar.','Seu próximo look começa com uma boa escolha.')}<section class="wrap contact-layout"><div><span class="eyebrow">ATENDIMENTO NARROWBORNE</span><h2>ENCONTRE A PEÇA.<br>CONFIRME OS DETALHES.</h2><p>Antes de comprar, confirme o modelo, o tamanho, as medidas, a disponibilidade e as condições de entrega.</p>${active?'<p>Prepare sua mensagem ao lado e continue a conversa no WhatsApp da loja.</p>':'<p>O canal de atendimento está em preparação. Você pode copiar sua consulta e guardá-la para quando o contato da loja estiver disponível.</p>'}${p?`<a class="text-link" href="#/produto/${esc(p.id)}">Voltar à peça selecionada ↗</a>`:'<a class="text-link" href="#/catalogo">Explorar o catálogo ↗</a>'}${insta?`<p style="margin-top:25px"><a class="text-link" href="${esc(config.instagram)}" target="_blank" rel="noopener noreferrer">Nosso Instagram ↗</a></p>`:''}</div><div class="contact-panel"><label for="contact-message">Sua consulta</label><textarea id="contact-message">${esc(message)}</textarea>${active?`<button class="btn" id="whatsapp" data-phone="${wa}">CONTINUAR NO WHATSAPP ↗</button>`:''}<button class="btn ${active?'outline':''}" id="copy-message">COPIAR CONSULTA ↗</button><p class="note">${active?'Você será direcionado ao WhatsApp e poderá revisar a mensagem antes de enviá-la.':'Copiar não envia a mensagem nem cria um pedido.'}</p></div></section>`;}
function about(){return `${pageTop('Sobre a Narrowborne.','Uma multimarcas urbana em construção, com seleção enxuta e atendimento direto.')}<section class="text-page"><span class="eyebrow">POR QUE A LOJA EXISTE</span><h2>ESCOLHER BEM DÁ MENOS TRABALHO.</h2><p>A Narrowborne nasce para reunir, em um só lugar, peças que conversam entre si. Camisetas, calças, moletons, bonés e acessórios entram no catálogo pelo caimento, pela combinação e pelo uso no dia a dia — não só pelo nome na etiqueta.</p><p>A proposta é simples: apresentar opções claras, informar o que realmente está disponível e ajudar o cliente a confirmar os detalhes antes de comprar.</p><h2>COMO O CATÁLOGO VAI FUNCIONAR.</h2><p>Cada produto será publicado com fotos, tamanhos, medidas e disponibilidade. Enquanto essa etapa não termina, a página de marcas mostra os nomes previstos para a primeira seleção.</p><a class="btn purple" href="#/marcas">VER MARCAS PREVISTAS ↗</a></section>`;}

function help(){const faqs=[['Já posso comprar pelo site?','Este é um catálogo em preparação. Não há checkout, cobrança ou confirmação de pedidos. Consulte o atendimento sobre a disponibilidade antes de comprar.'],['Por que as categorias ainda estão vazias?','Nosso catálogo está em preparação. As peças serão publicadas de acordo com a seleção e o estoque da loja. Por enquanto, não há produtos disponíveis no site.'],['Como escolho o tamanho?','Use a numeração de uma peça que veste bem como ponto de partida. Solicite as medidas da peça real à loja e compare largura do peito, comprimento e cintura. Os tamanhos variam entre marcas. Confirme as medidas da peça quando o catálogo estiver disponível.'],['Como funcionam entrega e trocas?','As condições de entrega, frete, prazos e trocas serão informadas pela loja antes de qualquer compra. Não há cálculo de frete ou promessa de prazo nesta versão.'],['Onde ficam os meus favoritos?','Eles ficam salvos no navegador do aparelho que você está usando. Ao limpar os dados do navegador, você também apaga a seleção. Não existe conta de usuário nesta versão.'],['Quando chegam os relógios?','A categoria está em preparação, sem data de lançamento confirmada. Acesse a seção Relógios para conhecer a proposta.']];return `${pageTop('Respostas diretas.','Tudo o que você precisa saber para explorar a seleção.')}<div class="text-page">${faqs.map(([q,a],i)=>`<details ${i===0?'open':''}><summary>${q}</summary><p>${a}</p></details>`).join('')}<p style="margin-top:30px"><a class="btn" href="#/atendimento">IR PARA ATENDIMENTO ↗</a></p></div>`;}
function privacy(){return `${pageTop('Privacidade.','Informações sobre os dados usados nesta versão do site.')}<div class="text-page"><h2>FAVORITOS NO SEU NAVEGADOR</h2><p>A seleção de favoritos é armazenada localmente neste navegador, usando localStorage. Não enviamos essa seleção a um servidor. Para apagá-la, remova os favoritos ou limpe os dados do site no navegador.</p><h2>BUSCA E CONSULTAS</h2><p>A busca é executada no seu aparelho. A consulta digitada no atendimento não é enviada por este site. Ao copiar, o texto vai para sua área de transferência. Se o WhatsApp estiver configurado, você poderá abrir o aplicativo e decidir se envia a mensagem.</p><h2>SERVIÇOS EXTERNOS</h2><p>Esta versão não inclui ferramentas de análise, pixels de publicidade ou formulários de cadastro. Ao acessar serviços externos, como WhatsApp ou Instagram, aplicam-se as políticas desses serviços. A plataforma de hospedagem pode registrar dados técnicos de acesso conforme sua própria política.</p><h2>CONTATO</h2><p>Os canais comerciais serão apresentados na página de atendimento assim que forem configurados pela loja.</p><a class="btn" href="#/atendimento">ATENDIMENTO ↗</a></div>`;}
function notFound(){return `${pageTop('Página não encontrada.')}<section class="wrap section">${empty('Vamos encontrar seu estilo.','Essa página não está no catálogo. Volte para a seleção e continue explorando.')}</section>`;}
let firstRender=true;
function route(){const raw=location.hash.slice(1)||'/';const [path,query='']=raw.split('?');const params=new URLSearchParams(query);let content,title;const segments=path.split('/').filter(Boolean);switch(segments[0]){case undefined:content=home();title='Estilo é identidade.';break;case 'catalogo':content=catalog(params);title=params.get('marca')||categories[params.get('categoria')]||'Catálogo';break;case 'produto':content=product(segments[1]);title=products.find(p=>p.id===segments[1])?.name||'Peça não encontrada';break;case 'marcas':content=brandPage();title='Marcas';break;case 'colecao':content=collection(segments[1]);title='Coleções';break;case 'favoritos':content=saved();title='Sua seleção';break;case 'acessorios':content=accessories();title='Acessórios';break;case 'relogios':content=watchBlock(true);title='Relógios — Em breve';break;case 'atendimento':content=contact(params);title='Atendimento';break;case 'sobre':content=about();title='Nossa identidade';break;case 'ajuda':content=help();title='Perguntas frequentes';break;case 'privacidade':content=privacy();title='Privacidade';break;default:content=notFound();title='Página não encontrada';}
if(observer)observer.disconnect();main.innerHTML=content;if(observer)main.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.title=title+' | NarrowBorne Store';document.getElementById('search').value=params.get('q')||'';document.getElementById('main-nav').classList.remove('open');document.getElementById('menu-toggle').setAttribute('aria-expanded','false');document.querySelectorAll('#main-nav a').forEach(a=>{const active=a.getAttribute('href')==='#'+raw;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
if(!firstRender){window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}firstRender=false;updateFavorites();
}
function updateFavorites(){document.getElementById('fav-count').textContent=favorites.length;document.querySelectorAll('[data-favorite]').forEach(b=>{const active=favorites.includes(b.dataset.favorite);b.setAttribute('aria-pressed',active);const p=products.find(p=>p.id===b.dataset.favorite);b.setAttribute('aria-label',(active?'Remover dos':'Adicionar aos')+' favoritos: '+(p?.name||''));});}
let toastTimer;
function toast(text){const t=document.getElementById('toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3000);}
document.addEventListener('click',async event=>{const b=event.target.closest('[data-favorite]');if(b){const id=b.dataset.favorite;const was=favorites.includes(id);favorites=was?favorites.filter(x=>x!==id):[...favorites,id];let persisted=true;try{localStorage.setItem('narrowborne:favoritos',JSON.stringify(favorites));}catch{persisted=false;}updateFavorites();if(location.hash.startsWith('#/favoritos'))route();toast(persisted?(was?'Peça removida da sua seleção.':'Peça salva na sua seleção.'):'Seleção atualizada nesta sessão. O navegador não permitiu salvá-la.');}
const size=event.target.closest('[data-size]');if(size){document.querySelectorAll('[data-size]').forEach(b=>b.setAttribute('aria-pressed',b===size));const link=document.getElementById('interest-link');const [base,query]=link.getAttribute('href').split('?');const p=new URLSearchParams(query);p.set('tamanho',size.dataset.size);link.href=base+'?'+p.toString();}
if(event.target.closest('#copy-message')){const field=document.getElementById('contact-message');try{await navigator.clipboard.writeText(field.value);toast('Consulta copiada.');}catch{field.focus();field.select();let copied=false;try{copied=document.execCommand('copy');}catch{}toast(copied?'Consulta copiada.':'Selecione o texto e use a opção Copiar do seu aparelho.');}}
const wa=event.target.closest('#whatsapp');if(wa){const text=document.getElementById('contact-message').value;window.open('https://wa.me/'+wa.dataset.phone+'?text='+encodeURIComponent(text),'_blank','noopener,noreferrer');}
});
document.getElementById('search-form').addEventListener('submit',e=>{e.preventDefault();location.hash=catalogUrl({q:document.getElementById('search').value.trim()}).slice(1);});
document.getElementById('menu-toggle').addEventListener('click',()=>{const nav=document.getElementById('main-nav');const open=nav.classList.toggle('open');document.getElementById('menu-toggle').setAttribute('aria-expanded',open);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.getElementById('main-nav').classList.remove('open');document.getElementById('menu-toggle').setAttribute('aria-expanded','false');}});
document.addEventListener('change',event=>{if(!['brand-filter','sort-filter'].includes(event.target.id))return;const params=new URLSearchParams((location.hash.split('?')[1]||''));const key=event.target.id==='brand-filter'?'marca':'ordem';params.set(key,event.target.value);location.hash='/catalogo?'+params.toString();});
const motionButton=document.getElementById('motion-toggle');
let motionPaused=false;try{motionPaused=localStorage.getItem('narrowborne:motion')==='paused';}catch{}
function applyMotion(){document.documentElement.classList.toggle('motion-paused',motionPaused);motionButton.setAttribute('aria-pressed',String(motionPaused));motionButton.setAttribute('aria-label',motionPaused?'Ativar animações':'Pausar animações');motionButton.textContent=motionPaused?'▶':'Ⅱ';}
motionButton.addEventListener('click',()=>{motionPaused=!motionPaused;try{localStorage.setItem('narrowborne:motion',motionPaused?'paused':'playing');}catch{}applyMotion();});applyMotion();
let pointerFrame=0;main.addEventListener('pointermove',e=>{if(motionPaused||matchMedia('(prefers-reduced-motion: reduce)').matches||e.pointerType==='touch')return;const hero=e.target.closest('.ink-hero');if(!hero||pointerFrame)return;pointerFrame=requestAnimationFrame(()=>{const r=hero.getBoundingClientRect();hero.style.setProperty('--mx',((e.clientX-r.left)/r.width-.5)*15+'px');hero.style.setProperty('--my',((e.clientY-r.top)/r.height-.5)*12+'px');pointerFrame=0;});});
let scrollFrame=0;window.addEventListener('scroll',()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;document.getElementById('scroll-progress').style.transform='scaleX('+(max>0?scrollY/max:0)+')';scrollFrame=0;});},{passive:true});
window.addEventListener('hashchange',route);document.getElementById('year').textContent=new Date().getFullYear();route();
})();
