const SUPABASE_URL='https://nseqwtiwsabglzqqwibb.supabase.co';
const SUPABASE_PUBLISHABLE='sb_publishable_uyaUYAq6OoVX_g6NG1tPug_CZQbbzky';
const SESSION_KEY='narrowborne-admin-session-v1';
let state={products:[],orders:[],settings:{},admin:{}};
let editingId='';

const $=id=>document.getElementById(id);
const money=cents=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((Number(cents)||0)/100);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function saveState(msg='Tudo certo',busy=false){const el=$('saveState');el.textContent=msg;el.style.color=busy?'#ddd':'#6f6'}
function session(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function setSession(v){v?sessionStorage.setItem(SESSION_KEY,JSON.stringify(v)):sessionStorage.removeItem(SESSION_KEY}

async function authFetch(path,options={}){return fetch(SUPABASE_URL+'/auth/v1'+path,{...options,headers:{'apikey':SUPABASE_PUBLISHABLE,'Content-Type':'application/json',...(options.headers||{})}})}
async function refreshSession(s){if(!s?.refresh_token)return null;const r=await authFetch('/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok)return null;const n=await r.json();setSession(n);return n}
async function api(resource,options={}){let s=session();if(!s?.access_token)throw new Error('Sessão encerrada.');let r=await fetch(`${SUPABASE_URL}/functions/v1/admin-api?resource=${encodeURIComponent(resource)}${options.query||''}`,{...options,headers:{'apikey':SUPABASE_PUBLISHABLE,'Authorization':'Bearer '+s.access_token,...(options.headers||{})}});if(r.status===401){s=await refreshSession(s);if(!s)throw new Error('Sessão encerrada.');r=await fetch(`${SUPABASE_URL}/functions/v1/admin-api?resource=${encodeURIComponent(resource)}${options.query||''}`,{...options,headers:{'apikey':SUPABASE_PUBLISHABLE,'Authorization':'Bearer '+s.access_token,...(options.headers||{})}})}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.message||'Não foi possível concluir.');return data}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';$('loginButton').disabled=true;$('loginButton').textContent='ENTRANDO...';try{const r=await authFetch('/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('loginEmail').value.trim(),password:$('loginPassword').value})});const data=await r.json();if(!r.ok)throw new Error(data.error_description||data.msg||'E-mail ou senha incorretos.');setSession(data);await boot()}catch(err){$('loginError').textContent=err.message}finally{$('loginButton').disabled=false;$('loginButton').textContent='ENTRAR'}});
$('logoutBtn').addEventListener('click',()=>{setSession(null);location.reload()});

async function boot(){try{saveState('Carregando...',true);const data=await api('dashboard');state=data;$('loginScreen').hidden=true;$('app').hidden=false;renderAll();fillStore();saveState('Sincronizado')}catch(err){setSession(null);$('loginScreen').hidden=false;$('app').hidden=true;$('loginError').textContent=err.message.includes('administrador')?'Seu login existe, mas ainda não foi autorizado como administrador.':err.message}}

function statusLabel(s=''){const map={approved:'Aprovado',paid:'Aprovado',created:'Criado',pending:'Pendente',creating_checkout:'Abrindo checkout',checkout_error:'Erro no checkout',cancelled:'Cancelado',rejected:'Recusado'};return map[s]||s||'—'}
function isPaid(s=''){return ['approved','paid'].includes(String(s).toLowerCase())}
function renderStats(){const active=state.products.filter(p=>p.active).length;const paid=state.orders.filter(o=>isPaid(o.status));$('statActive').textContent=active;$('statOrders').textContent=state.orders.length;$('statPaid').textContent=paid.length;$('statRevenue').textContent=money(paid.reduce((a,o)=>a+Number(o.amount_cents||0),0))}
function orderProducts(o){const cart=Array.isArray(o.cart)?o.cart:[];return cart.map(i=>`${i.name||i.id} · ${i.size||'-'} × ${i.quantity||1}`).join(', ')||'—'}
function renderRecent(){const rows=state.orders.slice(0,5);$('recentOrders').innerHTML=rows.length?`<table class="table"><tbody>${rows.map(o=>`<tr><td><strong>${esc(o.external_reference)}</strong><br><span class="muted">${new Date(o.created_at).toLocaleString('pt-BR')}</span></td><td>${esc(orderProducts(o))}</td><td><span class="pill ${isPaid(o.status)?'ok':''}">${esc(statusLabel(o.status))}</span></td><td><strong>${money(o.amount_cents)}</strong></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum pedido ainda.</div>'}
function renderProducts(){const host=$('productList');host.innerHTML=state.products.length?state.products.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(p=>`<article class="product-row"><div class="product-thumb">${p.image_path?`<img src="${esc(imageUrl(p.image_path))}" alt="">`:'NB'}</div><div class="product-main"><strong>${esc(p.name)}</strong><span>${esc(p.subtitle||'')}</span></div><div class="product-cell hide-small"><span>Preço</span><b>${p.price_cents==null?'Sem preço':money(p.price_cents)}</b></div><div class="product-cell hide-small"><span>Status</span><span class="pill ${p.active?'ok':'err'}">${p.active?'No site':'Oculto'}</span></div><button class="btn ghost" data-edit="${esc(p.id)}">EDITAR</button></article>`).join(''):'<div class="empty">Nenhum produto cadastrado.</div>';host.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.edit)))}
function renderOrders(){const q=$('orderSearch').value.toLowerCase();const st=$('orderStatus').value;const rows=state.orders.filter(o=>(!st||o.status===st)&&(!q||String(o.external_reference).toLowerCase().includes(q)||orderProducts(o).toLowerCase().includes(q)));$('ordersTable').innerHTML=rows.length?`<table class="table"><thead><tr><th>Pedido</th><th>Itens</th><th>Status</th><th>Valor</th><th>Data</th></tr></thead><tbody>${rows.map(o=>`<tr><td>${esc(o.external_reference)}</td><td>${esc(orderProducts(o))}</td><td><span class="pill ${isPaid(o.status)?'ok':o.status==='checkout_error'?'err':''}">${esc(statusLabel(o.status))}</span></td><td><strong>${money(o.amount_cents)}</strong></td><td>${new Date(o.created_at).toLocaleString('pt-BR')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nenhum pedido encontrado.</div>'}
function renderAll(){renderStats();renderRecent();renderProducts();renderOrders()}

function imageUrl(path=''){if(!path)return'';if(/^https?:/i.test(path)||path.startsWith('../')||path.startsWith('assets/'))return path.startsWith('assets/')?'../'+path:path;return `${SUPABASE_URL}/storage/v1/object/public/product-images/${path}`}
function centsFromInput(v){const s=String(v||'').trim();if(!s)return null;const n=Number(s.replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?Math.round(n*100):null}
function priceInput(c){return c==null?'':(Number(c)/100).toFixed(2).replace('.',',')}

function openProduct(id=''){editingId=id;const p=id?state.products.find(x=>x.id===id):null;$('productModalTitle').textContent=p?'Editar produto':'Novo produto';$('productId').value=p?.id||'';$('productName').value=p?.name||'';$('productSubtitle').value=p?.subtitle||'';$('productPrice').value=priceInput(p?.price_cents);$('productSort').value=p?.sort_order||0;$('productDescription').value=p?.description||'';$('productSizes').value=(p?.sizes||['P','M','G','GG']).join(', ');$('productStatus').value=p?.status_text||'';$('productTone').value=p?.tone||'black';$('productActive').checked=p?p.active!==false:true;$('productImagePath').value=p?.image_path||'';$('productPreview').src=p?.image_path?imageUrl(p.image_path):'';$('productPreview').style.visibility=p?.image_path?'visible':'hidden';$('deleteProductBtn').style.display=p?'inline-flex':'none';$('productModal').hidden=false}
function closeProduct(){$('productModal').hidden=true;editingId=''}
document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeProduct));$('newProductBtn').addEventListener('click',()=>openProduct());

$('productImageFile').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;saveState('Enviando foto...',true);try{const fd=new FormData();fd.append('file',file);const res=await api('upload',{method:'POST',body:fd});$('productImagePath').value=res.path;$('productPreview').src=res.public_url;$('productPreview').style.visibility='visible';toast('Foto enviada.');saveState('Foto pronta')}catch(err){toast(err.message);saveState('Erro ao enviar',true)}});

$('productForm').addEventListener('submit',async e=>{e.preventDefault();saveState('Salvando...',true);const body={id:$('productId').value||$('productName').value,name:$('productName').value,subtitle:$('productSubtitle').value,price_cents:centsFromInput($('productPrice').value),sort_order:Number($('productSort').value||0),description:$('productDescription').value,sizes:$('productSizes').value.split(',').map(s=>s.trim()).filter(Boolean),status_text:$('productStatus').value,tone:$('productTone').value,active:$('productActive').checked,image_path:$('productImagePath').value};try{await api('product',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await reloadDashboard();closeProduct();toast('Produto salvo. O site já usa esse valor.');saveState('Sincronizado')}catch(err){toast(err.message);saveState('Erro ao salvar',true)}});
$('deleteProductBtn').addEventListener('click',async()=>{if(!editingId||!confirm('Excluir este produto?'))return;try{await api('product',{method:'DELETE',query:'&id='+encodeURIComponent(editingId)});await reloadDashboard();closeProduct();toast('Produto excluído.')}catch(err){toast(err.message)}});

function fillStore(){const s=state.settings||{},b=s.brand||{},h=s.hero||{},d=s.drop_section||{},m=s.manifesto||{};$('brandName').value=b.name||'';$('brandDomain').value=b.domain||'';$('brandInstagram').value=b.instagram||'';$('brandWhatsapp').value=b.whatsapp||'';$('brandEmail').value=b.email||'';$('heroEyebrow').value=h.eyebrow||'';$('heroTop').value=h.titleTop||'';$('heroBottom').value=h.titleBottom||'';$('heroText').value=h.text||'';$('dropEyebrow').value=d.eyebrow||'';$('dropTitle').value=d.title||'';$('dropDescription').value=d.description||'';$('manifestoEyebrow').value=m.eyebrow||'';$('manifestoTitle').value=m.title||'';$('manifestoText').value=m.text||'';$('manifestoScripture').value=m.scripture||''}
$('saveStoreBtn').addEventListener('click',async()=>{const old=state.settings||{};const body={brand:{...(old.brand||{}),name:$('brandName').value,domain:$('brandDomain').value,instagram:$('brandInstagram').value,whatsapp:$('brandWhatsapp').value,email:$('brandEmail').value},hero:{...(old.hero||{}),eyebrow:$('heroEyebrow').value,titleTop:$('heroTop').value,titleBottom:$('heroBottom').value,text:$('heroText').value},drop:{...(old.drop_section||{}),eyebrow:$('dropEyebrow').value,title:$('dropTitle').value,description:$('dropDescription').value},manifesto:{...(old.manifesto||{}),eyebrow:$('manifestoEyebrow').value,title:$('manifestoTitle').value,text:$('manifestoText').value,scripture:$('manifestoScripture').value}};try{saveState('Salvando...',true);await api('settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await reloadDashboard();fillStore();toast('Loja atualizada.');saveState('Sincronizado')}catch(err){toast(err.message);saveState('Erro ao salvar',true)}});

async function reloadDashboard(){const data=await api('dashboard');state=data;renderAll()}
$('refreshOrdersBtn').addEventListener('click',async()=>{try{await reloadDashboard();toast('Pedidos atualizados.')}catch(err){toast(err.message)}});$('orderSearch').addEventListener('input',renderOrders);$('orderStatus').addEventListener('change',renderOrders);
document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.page)));document.querySelectorAll('[data-go]').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.go)));function go(page){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('page-'+page).classList.add('active');document.querySelector('.shell')?.scrollTo({top:0,behavior:'auto'})}

if(session())boot();
